name: 👾 Setup NeoVim
on:
  workflow_call:
    inputs:
      os:
        description: 'The operating system to run the setup on'
        required: true
        type: string
        default: 'ubuntu-latest'
      version:
        description: 'The version of NeoVim to install'
        required: true
        type: string
        default: 'stable'
jobs:
  neovim:
    name: 👽 Settingup NeoVim on Linux
    runs-on: ${{ github.event.inputs.os }}
    if: not startsWith(${{ github.event.inputs.os }}, 'windows')
    steps:
      - name: 📦 Install NeoVim
        shell: bash
        continue-on-error: true
        run: |
          mkdir -p /tmp/nvim
          wget -q https://github.com/neovim/neovim/releases/download/${{ github.event.inputs.version }}/nvim.appimage -O /tmp/nvim/nvim.appimage
          cd /tmp/nvim
          chmod a+x ./nvim.appimage
          ./nvim.appimage --appimage-extract
          chmod a+x ./squashfs-root/usr/bin/nvim
          echo "/tmp/nvim/squashfs-root/usr/bin/" >> $GITHUB_PATH
